import { Sora } from 'next/font/google'
import "./globals.css";
import Navbar from "./component/Navbar";
import DotPatternLinearGradient from "./component/card";
import { GlareCardDemo } from "./component/Glarecard";
import TeamCard from "./component/TeamCard";
import { CarouselCard } from "./component/CarouselCard";
import Footer from "./component/Footer";

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ['normal'],
  subsets: ['latin-ext'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased text-base_color`}
      >
        <Navbar />
        <main className="min-h-screen pt-16">{children}</main>
        
        <div className="b3x-ttokens-referral container mx-auto px-8 py-8 my-16 flex flex-col md:flex-row items-center justify-between bg-[#101115]">
          {/* Content - 50% width */}
          {/* <div className="text-center md:text-left self-start mb-4 md:mb-0 w-full md:w-1/3">
            <h4 className="text-2xl"> Get $10 worth of B3X Tokens!</h4>
            <p className="my-9">
              Earn $10 in B3X tokens by referring friends! B3X tokens offer
              governance rights, lower trading fees, and access to exclusive
              rewards, making them valuable for both traders and investors.
            </p>
          </div> */}
          <div className="md:ml-4 w-full md:w-1/2">
            <GlareCardDemo />
          </div>
        </div>
      <TeamCard/>
      
      <CarouselCard/>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
