import { Sora } from 'next/font/google'
import "./globals.css";
import Navbar from "./component/Navbar";
import DotPatternLinearGradient from "./component/card";
import { GlareCardDemo } from "./component/Glarecard";
import TeamCard from "./component/TeamCard";
import { CarouselCard } from "./component/CarouselCard";
import Footer from "./component/Footer";
import AdvisorsSection from '../app/advisors/page'
import TokenReferral from '../app/tokenReferral/page'

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ['normal'],
  subsets: ['latin-ext'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased text-base_color`}
      >
        <Navbar />
        <main className="min-h-screen pt-16">{children}</main>  

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
