import { Sora } from 'next/font/google'
import "./globals.css";
// import Navbar from "./component/Navbar";
import Footer from "./component/Footer/Footer";
import Navbar from './component/Navbar/Navbar';

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ['normal'],
  subsets: ['latin-ext'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased text-base_color`}
      >
        <Navbar />
        <main className="min-h-screen pt-16">{children}</main>  

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
